name: hudi_loader

on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      working-directory: glue

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Setup Pipenv
        run: |
          pip install pipenv
          # pipenv lock -r --dev > requirements.txt

      - name: Install Requirements
        run: |
          # python -m pip install -r requirements.txt
          pipenv shell
          pipenv install

      - name: Lint
        run: flake8
