name: hudi_loader

on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      working-directory: glue

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pipenv
        run: pip install pipenv

      - name: Lint
        run: |
          pipenv install --dev
          pipenv run lint
