name: hudi_loader

on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: glue

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Setup Pipenv
        run: pip install pipenv --dev

      - name: Cache Pipenv Environment
        id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Requirements
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install

      - name: Lint
        run: pipenv run flake8
