name: main

on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Build Project
        run: make build

      - name: Run Tests
        run: make test

      - name: Run Linting
        run: make lint

